<?php

/**
 * @file
 * Module file for aarhus_kommune_management.
 */

use Drupal\aarhus_kommune_management\Controller\SecurityController;
use Drupal\aarhus_kommune_management\Controller\DefaultController;
use Drupal\aarhus_kommune_management\Controller\UserController;
use Drupal\aarhus_kommune_management\Controller\Admin\TestController as AdminTestController;
use Drupal\aarhus_kommune_management\Service\UserManager;
use Psr\Http\Message\ResponseInterface;

/**
 * Implements hook_menu().
 */
function aarhus_kommune_management_menu() {
  $items['admin/config/services/aarhus-kommune-management'] = [
    'title' => 'Aarhus kommune management',
    'description' => 'Settings for aarhus-kommune-management',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['aarhus_kommune_management_admin_form'],
    'access arguments' => ['administer site configuration'],
    'type' => MENU_NORMAL_ITEM,
    'file' => 'aarhus_kommune_management.admin.inc',
  ];

  $items['admin/config/aarhus-kommune-management/test'] = [
    'page callback' => 'aarhus_kommune_management_router_admin',
    'access arguments' => ['administer site configuration'],
    'type' => MENU_CALLBACK,
    'delivery callback' => 'aarhus_kommune_management_deliver',
  ];

  $items['aarhus-kommune-management'] = [
    'page callback' => 'aarhus_kommune_management_router',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'delivery callback' => 'aarhus_kommune_management_deliver',
  ];

  return $items;
}

/**
 * Router.
 */
function aarhus_kommune_management_router() {
  $steps = arg();
  array_shift($steps);

  $controllerClass = DefaultController::class;

  composer_manager_register_autoloader();
  if (\count($steps) > 0) {
    switch ($steps[0]) {
      case 'authenticate':
        $controllerClass = SecurityController::class;
        break;

      case 'users';
        $controllerClass = UserController::class;
        break;
    }
  }

  try {
    $controller = call_user_func([$controllerClass, 'create']);
    return $controller->handle();
  }
  catch (\Exception $exception) {
    return [
      'error' => [
        'code' => $exception->getCode(),
        'message' => $exception->getMessage(),
      ]
    ];
  }
}

/**
 * Admin router.
 */
function aarhus_kommune_management_router_admin() {
  $steps = arg();
  array_shift($steps);

  $controller = AdminTestController::create();

  composer_manager_register_autoloader();

  try {
    $path = array_slice($steps, 3);
    return $controller->handle($path);
  }
  catch (\Exception $exception) {
    return [
      'error' => [
        'code' => $exception->getCode(),
        'message' => $exception->getMessage(),
      ]
    ];
  }
}

/**
 * Deliver result.
 */
function aarhus_kommune_management_deliver($result) {
  $accept = $_SERVER['HTTP_ACCEPT'];

  if ($result instanceof ResponseInterface) {
    foreach ($result->getHeaders() as $name => $value) {
      header($name . ': ' . $value);
    }
    echo (string) $result->getBody();
    exit;
  }

  drupal_json_output($result);
  exit;
}

/**
 * Get setting.
 */
function _aarhus_kommune_management_get_setting($path = NULL, $default_value = NULL) {
  $value = variable_get('aarhus_kommune_management');

  if (NULL !== $path) {
    $path = (array) $path;
    foreach ($path as $step) {
      if (!isset($value[$step])) {
        return $default_value;
      }
      $value = $value[$step];
    }
  }

  return $value;
}
