<?php

/**
 * @file
 * Module file for aarhus_kommune_management.
 */

use Drupal\aarhus_kommune_management\Controller\SecurityController;
use Drupal\aarhus_kommune_management\Controller\DefaultController;
use Drupal\aarhus_kommune_management\Controller\UserController;
use Psr\Http\Message\ResponseInterface;

/**
 * Implements hook_menu().
 */
function aarhus_kommune_management_menu() {
  $items['admin/config/aarhus-kommune-management'] = [
    'title' => 'aarhus-kommune-management/settings',
    'description' => 'Settings for aarhus-kommune-management',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['aarhus_kommune_management_admin_form'],
    'access arguments' => ['administer site configuration'],
    'type' => MENU_NORMAL_ITEM,
    'file' => 'aarhus_kommune_management.admin.inc',
  ];

  $items['aarhus-kommune-management'] = [
    'page callback' => 'aarhus_kommune_management_router',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'delivery callback' => 'aarhus_kommune_management_deliver',
  ];

  return $items;
}

/**
 * Router.
 */
function aarhus_kommune_management_router() {
  $steps = arg();
  array_shift($steps);

  $controller = new DefaultController();

  composer_manager_register_autoloader();
  if (\count($steps) > 0) {
    switch ($steps[0]) {
      case 'authenticate':
        $controller = new SecurityController();
        break;

      case 'users';
        $controller = new UserController();
        break;
    }
  }

  try {
    return $controller->handle();
  }
  catch (\Exception $exception) {
    return [
      'error' => [
        'code' => $exception->getCode(),
        'message' => $exception->getMessage(),
      ]
    ];
  }
}

/**
 * Authenticate.
 */
function aarhus_kommune_management_authenticate() {
  try {
    composer_manager_register_autoloader();
    $controller = new SecurityController();

    return $controller->handle();
  }
  catch (\Exception $exception) {
    return [
      'error' => [
        'code' => $exception->getCode(),
        'message' => $exception->getMessage(),
      ]
    ];
  }
}

/**
 * Users.
 */
function aarhus_kommune_management_users() {
  try {
    composer_manager_register_autoloader();
    $controller = new UserController();

    return $controller->handle();
  }
  catch (\Exception $exception) {
    return [
      'error' => [
        'code' => $exception->getCode(),
        'message' => $exception->getMessage(),
      ]
    ];
  }
}

/**
 * Deliver result.
 */
function aarhus_kommune_management_deliver($result) {
  $accept = $_SERVER['HTTP_ACCEPT'];

  if ($result instanceof ResponseInterface) {
    foreach ($result->getHeaders() as $name => $value) {
      header($name . ': ' . $value);
    }
    echo (string) $result->getBody();
    exit;
  }

  drupal_json_output($result);
  exit;
}

/**
 * Get setting.
 */
function _aarhus_kommune_management_get_setting($path = NULL, $default_value = NULL) {
  $value = variable_get('aarhus_kommune_management');

  if (NULL !== $path) {
    $path = (array) $path;
    foreach ($path as $step) {
      if (!isset($value[$step])) {
        return $default_value;
      }
      $value = $value[$step];
    }
  }

  return $value;
}
